import "./aquarium/wxhelper.js"

import "./tdl/base.js"
import "./tdl/fast.js"
import "./tdl/io.js"
import "./tdl/log.js"
import "./tdl/clock.js"
import "./tdl/math.js"
import "./tdl/fps.js"
import "./tdl/buffers.js"
import "./tdl/misc.js"
import "./tdl/models.js"
import "./tdl/particles.js"
import "./tdl/primitives.js"
import "./tdl/programs.js"
import "./tdl/screenshot.js"
import "./tdl/shader.js"
import "./tdl/string.js"
import "./tdl/sync.js"
import "./tdl/webgl.js"
import "./tdl/textures.js"

import "./aquarium/aquarium-shader.js"
import "./aquarium/aquarium-common.js"
import "./aquarium/aquarium.js"
